version: 2
updates:
  - package-ecosystem: "npm" # Specify the package manager (npm for Next.js)
    directory: "/" # Location of the `package.json` file
    schedule:
      interval: "weekly" # Run updates weekly
