export enum ROLE {
  USER = "USER",
  MANAGER = "MANAGER",
  ADMIN = "ADMIN",
}

export enum LEAVE_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
  APPROVED = "APPROVED",
}

export enum STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum LEAVE_TYPE {
  PAID = "PAID",
  UNPAID = "UNPAID",
}
